version: "3.8"

services:
  ui:
    build:
      context: ./ui/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api
      - mongodb

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=taskmgmntdb

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

