version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    environment:
      - PORT=9000
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB=taskmgmntdb
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:


